PROG = optical_spi_test
# SRC should only include necessary files
SRC = $(addprefix ../../src/,boost.c can_commands.c can_interface.c devices.c env_sensors.c heaters.c motors.c optical_spi.c)
include ../makefile
