PROG = can_commands_test
# SRC should only include necessary files
SRC = $(addprefix ../../src/,can_commands.c can_interface.c devices.c env_sensors.c general.c heaters.c motors.c optical_spi.c)
include ../makefile
